version: '3'
services:
  nginx:
    image: test-aapb-nginx
    ports:
      - "8080:80"
    # so we can see the aapb host
    depends_on: 
      - web

  solr:
    image: test-aapb-solr
    ports:
      - "8983:8983"
      
  web:
    # so we wait for solr
    depends_on:
      - solr
    image: test-aapb
    volumes:
      - bundle:/var/bundle

volumes:
  bundle: