version: '3'
services:
  nginx:
    # environment:
    #   # change this!
    #   - AAPB_ENV=dev
    image: test-aapb-nginx
    ports:
      - "8080:80"
    volumes:
      - sockets:/var/sockets
    # so we can see the aapb host
    depends_on: 
      - web

  solr:
    image: test-aapb-solr
    ports:
      - "8983:8983"
    volumes:
      - sockets:/var/sockets
      
  web:
    # so we wait for solr
    depends_on:
      - solr
    image: test-aapb
    volumes:
      - sockets:/var/sockets
      - bundle:/var/bundle

volumes:
  sockets:
  bundle: