version: '3'
services:
  web:
    image: aapb
    ports:
      - "3000:3000"
    volumes:
      - sockets:/var/sockets
  nginx:
    image: test-aapb-nginx
    ports:
      - "8080:80"
    volumes:
      - sockets:/var/sockets

  solr:
    image: test-aapb-solr
    ports:
      - "8983:8983"
    volumes:
      - sockets:/var/sockets

# no jettywrapper if you gon do this!
#  solr:
#    image: solr:6.6.6

volumes:
  sockets: