version: '3'
services:
  web:
    image: aapb
    ports:
      - "3000:3000"
    volumes:
      - sockets:/var/puma
  nginx:
    image: test-aapb-nginx
    ports:
      - "8080:80"
    volumes:
      - sockets:/var/puma
# no jettywrapper if you gon do this!
#  solr:
#    image: solr:6.6.6

volumes:
  sockets: